### ISSUE TITLE
Why isn't a Basic Installation Guide?

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [StreisandEffect/discussions#164]
Why isn't there a basic guide to make this work?
Like i am using android mobile. And have a Windows PC. Now i can have access to Aws or Digital Oceon or GCloud. How can i deploy it on cloud and use on my android to bypass restricted Internet sites?

**Comment by cpu** [comment]
@ParveenBhadooOfficial The [project README](https://github.com/StreisandEffect/streisand/blob/master/README.md) is the only guide available. If you have ideas for better ways to present the information I recommend you submit a pull-request.

If you aren't able to follow the existing README I recommend you look into alternative projects like [Outline](https://getoutline.org/en/home) that offer a more stream lined user experience that might be more appropriate for someone without existing Linux system administration skill.
